#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-java-boot-classpath-detector
Version  : 1.15
Release  : 1
URL      : https://repo1.maven.org/maven2/org/codehaus/mojo/java-boot-classpath-detector/1.15/java-boot-classpath-detector-1.15.jar
Source0  : https://repo1.maven.org/maven2/org/codehaus/mojo/java-boot-classpath-detector/1.15/java-boot-classpath-detector-1.15.jar
Source1  : https://repo1.maven.org/maven2/org/codehaus/mojo/java-boot-classpath-detector/1.15/java-boot-classpath-detector-1.15.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-java-boot-classpath-detector-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-java-boot-classpath-detector package.
Group: Data

%description data
data components for the mvn-java-boot-classpath-detector package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/java-boot-classpath-detector/1.15
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/java-boot-classpath-detector/1.15

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/java-boot-classpath-detector/1.15
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/codehaus/mojo/java-boot-classpath-detector/1.15


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/codehaus/mojo/java-boot-classpath-detector/1.15/java-boot-classpath-detector-1.15.jar
/usr/share/java/.m2/repository/org/codehaus/mojo/java-boot-classpath-detector/1.15/java-boot-classpath-detector-1.15.pom
